name: 'Set a reviewer and an assignee'
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: uesteibar/reviewer-lottery@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: danielswensson/auto-assign-owner-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
